// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"flightAPI/server/models"
)

// UploadFileCreatedCode is the HTTP code returned for type UploadFileCreated
const UploadFileCreatedCode int = 201

/*UploadFileCreated Uploaded

swagger:response uploadFileCreated
*/
type UploadFileCreated struct {
}

// NewUploadFileCreated creates UploadFileCreated with default headers values
func NewUploadFileCreated() *UploadFileCreated {

	return &UploadFileCreated{}
}

// WriteResponse to the client
func (o *UploadFileCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*UploadFileDefault error

swagger:response uploadFileDefault
*/
type UploadFileDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUploadFileDefault creates UploadFileDefault with default headers values
func NewUploadFileDefault(code int) *UploadFileDefault {
	if code <= 0 {
		code = 500
	}

	return &UploadFileDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the upload file default response
func (o *UploadFileDefault) WithStatusCode(code int) *UploadFileDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the upload file default response
func (o *UploadFileDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the upload file default response
func (o *UploadFileDefault) WithPayload(payload *models.Error) *UploadFileDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload file default response
func (o *UploadFileDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadFileDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
