// Code generated by go-swagger; DO NOT EDIT.

// Package restapi A Todo list application
//
//  From the todo list tutorial on goswagger.io
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/io.goswagger.examples.todo-list.v1+json
//    - multipart/form-data
//
//  Produces:
//    - application/octet-stream
//    - application/io.goswagger.examples.todo-list.v1+json
//
// swagger:meta
package restapi
